name: flutter_starter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  flutter_dotenv: ^5.0.2
  sentry_flutter: ^6.9.0
  get_it: ^7.2.0
  connectivity_plus: ^2.3.6
  rxdart: ^0.27.5
  get: ^4.6.5
  dio: ^4.0.6 
  retrofit: ^3.0.1+1
  logger: ^1.1.0
  speed_up_get: ^0.0.2
  speed_up: ^0.8.3
  speed_up_flutter: ^0.8.4
  fluent_result: ^7.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.5
  package_info_plus: ^1.4.3
  freezed_annotation: ^2.1.0
  device_info_plus: ^4.0.1
  equatable: ^2.0.3
  event_bus_plus: ^0.2.2

  # UI
  cupertino_icons: ^1.0.2
  auto_route: ^4.2.1
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.1.0
  flutter_svg: ^1.1.1+1
  intl: ^0.17.0
  cached_network_image: ^3.2.1

  # 
  # permission_handler: ^10.0.0
  # notification_permissions: ^0.6.1
  # app_settings: ^4.1.8


dev_dependencies:
  auto_route_generator: ^4.2.0
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  hive_generator: ^1.1.3
  retrofit_generator: ^4.0.3
  shouldly: ^0.5.0+1
  # given_when_then_unit_test: 
  golden_toolkit: ^0.13.0
  mocktail: ^0.3.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    - assets/images/
    
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
